FROM openjdk:8-jdk-alpine
FROM maven:3
LABEL "Maintainer"="blackdogg"

ADD . /usr/local/docker-git-hello-world
RUN cd /usr/local/docker-git-hello-world
RUN mvn clean install package
CMD ["java", "-cp", "/usr/local/docker-git-hello-world/target/docker-git-hello-world-0.0.1-SNAPSHOT.jar", "pe.com.udemy.HelloWorldPing"]